package Model.Spell;

public enum SpellArea {
    FRIENDLY_MONSTERFIELD,FRIENDLY_SPELLFIELD,FRIENDLY_HAND,FRIENDLY_DECK,FRIENDLY_GRAVEYARD,FRIENDLY_PLAYER,
    ENEMY_MONSTERFIELD,ENEMY_SPELLFIELD,ENEMY_HAND,ENEMY_DECK,ENEMY_GRAVEYARD,ENEMY_PLAYER
}
